version: '2'
services:
  redis:
    image: redis


  ebdstatus:
    image: crossref/event-data-status:0.1.2
    expose:
     - "8003"
    ports:
     - "8003:8003"
    depends_on:
     - redis
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - REDIS_DB=0
     - PORT=8003
     - JWT_SECRETS=TEST,TEST2
    command: "lein run"

  demo:
    build: .
    volumes:
     - .:/user/src/app
     - ./.m2-cache:/home/deploy/.m2
    depends_on:
     - redis
     - ebdstatus
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - REDIS_DB=0
     - JWT_SECRETS=TEST,TEST2
     - STORAGE=redis
     - PORT=8002
     - STATUS_SERVICE=http://ebdstatus:8003
     - BROADCAST-LIVEDEMO-JWT=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyIxIjoiMSIsInN1YiI6Indpa2lwZWRpYSJ9.w7zV2vtKNzrNDfgr9dfRpv6XYnspILRli_V5vd1J29Q
     - BROADCAST-LIVEDEMO-ENDPOINT=http://138.201.202.133:8101/events
     - BROADCAST-LIVEDEMO-NAME=live-demo
     - BROADCAST-LIVEDEMO-TYPE=live
    command: "lein test :component"



