version: '2'
services:
  test:
    build: .
    user: deploy
    volumes:
     - .:/code
     - ./.m2-cache:/home/deploy/.m2
    depends_on:
     - redis
    environment:
     - REDIS_HOST=redis
     - REDIS_PORT=6379
     - REDIS_DB=0
     - JWT_SECRETS=TEST,TEST2
     - STORAGE=s3
     - S3_KEY=${S3_KEY}
     - S3_SECRET=${S3_SECRET}
     - S3_BUCKET_NAME=${S3_BUCKET_NAME}
     - S3_REGION_NAME=${S3_REGION_NAME}
    command: "lein test :integration"

  redis:
    image: redis
