version: '2'
services:
  test:
    build: .
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    environment:
     - GLOBAL_JWT_SECRETS=TEST,TEST2
     - BUS_STORAGE=memory
     - BUS_BROADCAST_CONFIG=resources/test/broadcast-config.json
    command: "lein test :unit"
