version: '2'
services:
  redis:
    image: redis


  test:
    build: .
    volumes:
     - .:/usr/src/app
     - ./.m2-cache:/root/.m2
    depends_on:
     - redis
    environment:
     - BUS_REDIS_HOST=redis
     - BUS_REDIS_PORT=6379
     - BUS_REDIS_DB=0
     - GLOBAL_JWT_SECRETS=TEST,TEST2
     - BUS_STORAGE=redis
     - BUS_PORT=8002
     - BUS_BROADCAST_CONFIG=resources/test/broadcast-config.json
    command: "lein test :component"



